### ISSUE TITLE
Did you use MAML like method to train your model?

### ISSUE THREAD

**Issue by lihuiliullh** [zjukg/MorsE#3]
Did you use MAML like method to train your model? If not, where is the meta part?

**Comment by AnselCmy** [comment]
Hello, thank you for contacting us. In this work, we didn't use optimization-based meta-learning and the "inner loop" like MAML. The learning regime that trains the model based on tasks containing support and query sets can be viewed as "learning to learn". Furthermore, our methods can also be considered a black-box method that trains black-box meta-learners (e.g., neural networks) to output model parameters.
